/**
 * AlphaEarth Case Studies Database
 * 125 Educational Scenarios for Satellite Embedding Exploration
 *
 * The AlphaEarth Foundations Satellite Embedding dataset is produced by
 * Google and Google DeepMind.
 *
 * Note: AlphaEarth bands are zero-indexed: A00-A63 (64 bands total)
 */

const CaseStudies = {
    categories: [
        {
            id: 'deforestation',
            name: 'Deforestation & Forest Dynamics',
            icon: '🌲',
            scenarios: [
                { id: 1, name: 'Amazon Deforestation Arc', lat: -8.5, lon: -55.0, zoom: 8, year1: 2017, year2: 2024, description: 'Monitor the "Arc of Deforestation" along Brazil\'s agricultural frontier where forest is converted to cattle ranching and soy production.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "You're viewing change detection between 2017 and 2024 in Rondônia, Brazil. White areas indicate stable forest with high similarity scores, while dark patches reveal deforestation—notice the distinctive 'fishbone' pattern branching from roads. The geometric, linear clearing corridors demonstrate how road construction drives systematic forest loss in the Amazon." },
                { id: 2, name: 'Borneo Palm Oil Expansion', lat: 1.5, lon: 117.0, zoom: 9, year1: 2017, year2: 2023, description: 'Track conversion of tropical rainforest to palm oil plantations in Indonesian and Malaysian Borneo.', bands: ['A01', 'A13', 'A07'], mode: 'change', explainer: "This change detection reveals palm oil plantation expansion in Borneo between 2017 and 2024. Dark areas show where native rainforest was converted to plantations—notice the geometric, rectangular shapes characteristic of industrial agriculture. The sharp boundaries between white (stable) and dark (changed) areas highlight the stark contrast between intact forest and plantation monoculture." },
                { id: 3, name: 'Congo Basin Logging Roads', lat: 1.0, lon: 18.0, zoom: 8, year1: 2018, year2: 2024, description: 'Observe logging road network expansion into pristine Central African rainforest.', bands: ['A00', 'A11', 'A06'], mode: 'change', explainer: "Change detection in the Congo Basin shows a different deforestation pattern than the Amazon. Dark areas indicating change are more scattered and localized around settlements rather than forming large industrial clearings. This reflects smallholder-driven deforestation for subsistence agriculture rather than large-scale commercial operations." },
                { id: 4, name: 'Sumatra Peat Forest Loss', lat: 0.5, lon: 103.0, zoom: 9, year1: 2017, year2: 2022, description: 'Monitor peat swamp forest destruction and drainage for agriculture in Riau Province.', bands: ['A02', 'A14', 'A09'], mode: 'change', explainer: "You're viewing fire impacts on Sumatra's carbon-rich peatlands. Dark patches indicate areas where fire dramatically altered the landscape's embedding signature. Peat fires are particularly concerning because they release massive amounts of stored carbon and can burn underground for months, making them extremely difficult to extinguish." },
                { id: 5, name: 'Chaco Dry Forest Clearing', lat: -24.0, lon: -62.0, zoom: 8, year1: 2017, year2: 2024, description: 'Track rapid agricultural expansion into South America\'s Gran Chaco dry forest ecosystem.', bands: ['A03', 'A17', 'A10'], mode: 'change', explainer: "You're viewing rapid agricultural expansion in Argentina's Gran Chaco dry forest. Dark areas show conversion from native woodland to soy cultivation between 2017 and 2024. The Chaco is experiencing some of the world's fastest deforestation rates, driven by global demand for soybeans used in animal feed and cooking oil." },
                { id: 6, name: 'Madagascar Eastern Forests', lat: -18.5, lon: 48.5, zoom: 9, year1: 2017, year2: 2023, description: 'Monitor slash-and-burn agriculture impacts on unique Madagascar rainforests.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "This analysis reveals forest fragmentation in Madagascar's eastern rainforest corridor. Dark changed areas show where forest has been cleared, while remaining white patches represent increasingly isolated forest fragments. This fragmentation threatens Madagascar's unique endemic species by reducing habitat connectivity and increasing edge effects." },
                { id: 7, name: 'Cerrado Savanna Conversion', lat: -14.0, lon: -47.0, zoom: 8, year1: 2018, year2: 2024, description: 'Observe agricultural transformation of Brazil\'s species-rich Cerrado savanna.', bands: ['A04', 'A18', 'A11'], mode: 'change', explainer: "This analysis spans the ecological transition zone between Amazon rainforest and Cerrado savanna. Notice how deforestation patterns differ between biomes: the Amazon shows large clearing blocks while the Cerrado exhibits more dispersed conversion. Different ecosystems require different conservation strategies based on their unique land use dynamics." },
                { id: 8, name: 'Myanmar Teak Extraction', lat: 19.5, lon: 96.5, zoom: 9, year1: 2017, year2: 2022, description: 'Track selective logging patterns in Myanmar\'s valuable teak forests.', bands: ['A01', 'A13', 'A07'], mode: 'change', explainer: "This 8-cluster analysis reveals the internal diversity of Myanmar's teak forests. Different colors represent distinct forest types: primary forest, secondary growth, selectively logged areas, and agricultural clearings. Selective logging creates different patterns than clearcut harvesting, visible as scattered rather than consolidated changes." },
                { id: 9, name: 'Siberian Taiga Wildfires', lat: 63.0, lon: 125.0, zoom: 7, year1: 2019, year2: 2021, description: 'Observe massive wildfire scars in Siberian boreal forests linked to climate change.', bands: ['A05', 'A19', 'A12'], mode: 'change', explainer: "You're viewing the aftermath of massive wildfires in Siberia's boreal forests. Dark areas show severe burn scars where fire dramatically altered forest structure. Unlike logging (which creates geometric patterns), wildfire creates irregular, organic shapes that follow topography, wind patterns, and fuel conditions." },
                { id: 10, name: 'Papua New Guinea Highlands', lat: -5.5, lon: 145.0, zoom: 9, year1: 2017, year2: 2023, description: 'Monitor forest clearing for subsistence agriculture in PNG highlands.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "Change detection in Papua New Guinea shows scattered forest disturbance patterns. Dark areas indicating change are localized around highland settlements, reflecting smallholder-driven clearing for subsistence agriculture rather than large-scale commercial operations. The mountainous terrain constrains agricultural expansion." },
                { id: 11, name: 'Canadian Boreal Mining', lat: 56.0, lon: -111.0, zoom: 8, year1: 2017, year2: 2024, description: 'Track oil sands mining impact on Alberta\'s boreal forest ecosystem.', bands: ['A06', 'A20', 'A13'], mode: 'change', explainer: "This change detection captures two types of forest disturbance: logging and mining operations. Geometric rectangular dark patches indicate clearcut logging and mining pits, while more irregular patterns may show road construction and processing facilities. The challenge for forest managers is distinguishing between these disturbance types." },
                { id: 12, name: 'Laos Rubber Plantations', lat: 19.0, lon: 102.0, zoom: 9, year1: 2017, year2: 2022, description: 'Observe forest conversion to rubber monocultures in northern Laos.', bands: ['A02', 'A16', 'A09'], mode: 'change', explainer: "This analysis attempts to distinguish different plantation types in northern Laos. Rubber plantations and remaining natural forest each have distinct embedding signatures. Look for geometric plantation boundaries (straight lines, regular shapes) contrasting with the irregular edges of remaining natural forest." },
                { id: 13, name: 'California Wildfire Recovery', lat: 38.5, lon: -122.5, zoom: 9, year1: 2017, year2: 2024, description: 'Monitor forest regeneration after major California wildfires.', bands: ['A07', 'A21', 'A14'], mode: 'change', explainer: "This analysis shows the impact of California's wildfires and subsequent recovery. Dark areas indicate severe fire damage, while areas returning to lighter colors show vegetation regrowth. These fires were unprecedented in their intensity and extent, raising questions about climate change impacts on fire regimes." },
                { id: 14, name: 'Southeast Asia Mangroves', lat: 10.0, lon: 106.5, zoom: 9, year1: 2017, year2: 2023, description: 'Track mangrove forest loss and restoration in Mekong Delta region.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "Change detection reveals climate pressures on this critical mangrove ecosystem. Dark areas show mangrove loss from sea level rise, increased storm intensity, and human encroachment. As seas rise, mangroves face squeeze between advancing ocean and densely populated land—with limited room to migrate inland." },
                { id: 15, name: 'European Bark Beetle Damage', lat: 48.5, lon: 13.5, zoom: 9, year1: 2018, year2: 2023, description: 'Observe bark beetle epidemic impacts on Central European spruce forests.', bands: ['A08', 'A22', 'A15'], mode: 'change', explainer: "You're viewing Europe's ancient forest, spanning Poland and Czech Republic. Dark patches indicate bark beetle damage and salvage logging. The predominantly white/light coloring in undisturbed areas indicates remarkable stability—providing a baseline for comparison with disturbed forests." }
            ]
        },
        {
            id: 'agriculture',
            name: 'Agricultural Landscapes',
            icon: '🌾',
            scenarios: [
                { id: 16, name: 'Nile Delta Agriculture', lat: 30.8, lon: 31.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore intensive irrigated agriculture patterns in Egypt\'s fertile Nile Delta.', bands: ['A09', 'A23', 'A16'], mode: 'embeddings', explainer: "This clustering reveals one of Earth's sharpest ecological boundaries: the Nile Delta. The abrupt transition between lush irrigated farmland (green clusters) and barren desert (tan clusters) demonstrates how water availability completely determines land productivity. Every cultivated field exists because of irrigation from the Nile River." },
                { id: 17, name: 'US Corn Belt Patterns', lat: 41.5, lon: -93.0, zoom: 8, year1: 2020, year2: 2020, description: 'Analyze center-pivot irrigation and crop rotation in Iowa\'s agricultural heartland.', bands: ['A10', 'A24', 'A17'], mode: 'embeddings', explainer: "This 12-cluster analysis segments the American agricultural heartland into distinct farming systems. Different colors represent corn fields, soybean rotations, pasture, and urban areas. The Corn Belt produces a significant portion of America's grain on some of the world's most productive farmland." },
                { id: 18, name: 'Punjab Wheat Fields', lat: 30.5, lon: 75.0, zoom: 8, year1: 2020, year2: 2020, description: 'Observe intensive wheat cultivation in India\'s breadbasket region.', bands: ['A11', 'A25', 'A18'], mode: 'embeddings', explainer: "This clustering maps South Asia's most productive agricultural region spanning India and Pakistan. The uniform coloring indicates intensive irrigated monoculture—primarily wheat and rice—made possible by extensive canal networks. Punjab's 'Green Revolution' success feeds hundreds of millions but has depleted groundwater and degraded soils." },
                { id: 19, name: 'Brazilian Soy Frontier', lat: -12.5, lon: -55.5, zoom: 8, year1: 2017, year2: 2024, description: 'Track soybean expansion into Mato Grosso\'s former forest and cerrado lands.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "Change detection shows massive conversion of Brazil's Cerrado savanna to soy cultivation. Dark areas reveal the scale of transformation between 2017 and 2024. While Amazon deforestation gets headlines, the Cerrado is being destroyed faster—and it harbors unique biodiversity found nowhere else on Earth." },
                { id: 20, name: 'Dutch Greenhouse Agriculture', lat: 52.0, lon: 4.5, zoom: 10, year1: 2020, year2: 2020, description: 'Explore high-tech greenhouse clusters in Netherlands\' Westland region.', bands: ['A12', 'A26', 'A19'], mode: 'embeddings', explainer: "You're viewing land that shouldn't exist—the Netherlands' reclaimed polders lie below sea level, protected by dikes and pumps. Clustering reveals geometric precision: rectangular greenhouse clusters, straight canals, and planned settlements. This is humanity's most ambitious landscape engineering, turning seafloor into highly productive farmland." },
                { id: 21, name: 'California Central Valley', lat: 36.5, lon: -120.0, zoom: 8, year1: 2018, year2: 2022, description: 'Monitor drought impacts and fallowing in California\'s agricultural region.', bands: ['A13', 'A27', 'A20'], mode: 'change', explainer: "You're viewing how farmers responded to drought conditions between 2018 and 2022. Dark areas show fields that were fallowed (left unplanted) due to water scarcity. This reveals the human decisions embedded in the landscape—farmers must choose which crops to sacrifice when water allocations are reduced." },
                { id: 22, name: 'Mekong Rice Paddies', lat: 10.5, lon: 106.0, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze triple-cropping rice systems in Vietnam\'s Mekong Delta.', bands: ['A14', 'A28', 'A21'], mode: 'embeddings', explainer: "This 8-cluster analysis reveals the agricultural complexity of Vietnam's 'rice bowl.' Different colors distinguish rice paddies in various growth stages, shrimp aquaculture ponds, fruit orchards, and waterways. The Mekong Delta's intricate mosaic of land and water supports diverse farming systems feeding millions." },
                { id: 23, name: 'Ethiopian Highlands Farming', lat: 9.0, lon: 38.5, zoom: 9, year1: 2020, year2: 2020, description: 'Observe traditional highland agriculture patterns in Ethiopia.', bands: ['A15', 'A29', 'A22'], mode: 'embeddings', explainer: "This 10-cluster analysis reveals how elevation shapes agriculture in Ethiopia's highlands. Different colors correspond to distinct crop zones: coffee in mid-elevations, teff and barley higher up, and pastoral land at the margins. The terraced hillsides visible as textured patterns represent generations of agricultural engineering." },
                { id: 24, name: 'Australian Wheat Belt', lat: -32.0, lon: 118.0, zoom: 8, year1: 2019, year2: 2020, description: 'Compare drought vs normal year in Western Australia\'s wheat region.', bands: ['A16', 'A30', 'A23'], mode: 'change', explainer: "You're viewing Australia's 'food bowl' during severe drought. Dark areas show how water scarcity transformed irrigated farmland between 2019 and 2020. The Murray-Darling Basin produces 40% of Australia's agricultural output—its vulnerability to drought has national economic and food security implications." },
                { id: 25, name: 'Ukraine Grain Fields', lat: 49.0, lon: 32.5, zoom: 8, year1: 2021, year2: 2023, description: 'Monitor agricultural disruption in Ukraine\'s productive farmland.', bands: ['A17', 'A31', 'A24'], mode: 'change', explainer: "This temporal comparison spans the war years: 2021 to 2023. Observe changes in Ukraine's agricultural heartland—the 'breadbasket of Europe.' Conflict disrupts planting cycles, damages infrastructure, and renders farmland inaccessible, with global food security implications." },
                { id: 26, name: 'Israel Precision Agriculture', lat: 32.0, lon: 35.0, zoom: 10, year1: 2020, year2: 2020, description: 'Explore advanced drip irrigation and intensive farming in Negev region.', bands: ['A18', 'A32', 'A25'], mode: 'embeddings', explainer: "This change detection tells a story of agricultural innovation. Israel's drip irrigation and precision farming techniques have made the desert bloom. Different colors distinguish irrigated crops, orchards, and remaining desert—demonstrating how technology can overcome natural water scarcity." },
                { id: 27, name: 'Japanese Rice Terraces', lat: 37.5, lon: 138.0, zoom: 11, year1: 2020, year2: 2020, description: 'Observe traditional terraced rice paddies in Niigata Prefecture.', bands: ['A19', 'A33', 'A26'], mode: 'embeddings', explainer: "This clustering maps the famous wine and rice region where geography determines crop quality. Terraced paddies on hillsides (one cluster) differ from valley-floor agriculture (another cluster). The concept of 'terroir'—how location affects production—is literally visible in embedding space as distinct land classifications." },
                { id: 28, name: 'Spanish Olive Groves', lat: 37.8, lon: -4.5, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze extensive olive cultivation in Andalusia, Spain.', bands: ['A20', 'A34', 'A27'], mode: 'embeddings', explainer: "This clustering reveals the vast scale of olive cultivation in Andalusia. Different colors distinguish ancient olive groves with irregular spacing from modern intensive plantations with geometric precision. Spain produces half the world's olive oil, and these patterns reflect centuries of agricultural tradition." },
                { id: 29, name: 'Kenyan Flower Farms', lat: -0.3, lon: 36.3, zoom: 10, year1: 2020, year2: 2020, description: 'Explore commercial floriculture around Lake Naivasha, Kenya.', bands: ['A21', 'A35', 'A28'], mode: 'embeddings', explainer: "This clustering maps commercial floriculture around Lake Naivasha. Different colors distinguish greenhouses, open-field flower cultivation, and remaining natural vegetation. Kenya exports billions of flowers annually to Europe—this high-value agriculture has transformed the landscape while straining local water resources." },
                { id: 30, name: 'Argentine Pampas', lat: -35.0, lon: -61.0, zoom: 8, year1: 2020, year2: 2020, description: 'Observe large-scale grain and cattle operations in the Pampas.', bands: ['A22', 'A36', 'A29'], mode: 'embeddings', explainer: "Change detection in established agricultural regions shows remarkable stability (predominantly similar colors). Unlike frontier areas with active conversion, mature farmland maintains consistent embedding signatures year after year. This stability reflects established infrastructure, water rights, and farming practices that change slowly." }
            ]
        },
        {
            id: 'urban',
            name: 'Urban Expansion & Development',
            icon: '🏙️',
            scenarios: [
                { id: 31, name: 'Dubai Urban Growth', lat: 25.2, lon: 55.3, zoom: 10, year1: 2017, year2: 2024, description: 'Track rapid urban development and artificial island expansion in Dubai.', bands: ['A23', 'A37', 'A30'], mode: 'change', explainer: "Change detection shows Dubai literally building new land. Dark areas reveal artificial islands, reclaimed coastline, and massive construction projects completed since 2017. Dubai demonstrates how wealth and engineering can reshape geography—creating real estate from seawater in one of Earth's harshest environments." },
                { id: 32, name: 'Lagos Megacity Expansion', lat: 6.5, lon: 3.4, zoom: 10, year1: 2017, year2: 2024, description: 'Monitor Africa\'s fastest-growing megacity spreading into lagoon and forest areas.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "You're viewing one of the world's fastest-growing cities expanding across its lagoon-dotted landscape. Dark areas show informal settlement expansion and new development since 2017. Lagos adds roughly 77 people per hour, creating unprecedented pressure on infrastructure, housing, and natural systems." },
                { id: 33, name: 'Beijing Urban Sprawl', lat: 40.0, lon: 116.5, zoom: 9, year1: 2017, year2: 2023, description: 'Observe suburban expansion and new town development around Beijing.', bands: ['A24', 'A38', 'A31'], mode: 'change', explainer: "You're viewing continued transformation of Beijing's metropolitan region. Dark areas show new construction, suburban development, and infrastructure expansion. Beijing exemplifies Chinese urban development: rapid expansion planned and executed at a scale unprecedented in human history." },
                { id: 34, name: 'Dhaka Bangladesh Growth', lat: 23.8, lon: 90.4, zoom: 10, year1: 2017, year2: 2024, description: 'Track urbanization of floodplain areas in rapidly growing Dhaka.', bands: ['A25', 'A39', 'A32'], mode: 'change', explainer: "You're viewing one of the world's most densely populated cities expanding into flood-prone lowlands. Dark areas show new development in areas vulnerable to monsoon flooding and sea level rise. Dhaka's growth illustrates the tension between urgent housing needs and climate risk in developing megacities." },
                { id: 35, name: 'Phoenix Desert Sprawl', lat: 33.5, lon: -112.0, zoom: 9, year1: 2017, year2: 2024, description: 'Monitor urban expansion into Sonoran Desert around Phoenix, Arizona.', bands: ['A26', 'A40', 'A33'], mode: 'change', explainer: "Change detection reveals Phoenix's rapid expansion into surrounding desert. Dark areas at the urban fringe show new subdivisions built between 2017 and 2024. This growth pattern—low-density sprawl into desert—raises questions about water sustainability and urban heat island effects in a warming climate." },
                { id: 36, name: 'Cairo Informal Settlements', lat: 30.0, lon: 31.3, zoom: 10, year1: 2018, year2: 2023, description: 'Observe growth of informal housing on agricultural land near Cairo.', bands: ['A27', 'A41', 'A34'], mode: 'change', explainer: "Change detection shows urban expansion consuming prime agricultural land around Cairo. Dark areas indicate where buildings have replaced farms between 2018 and 2023. Egypt faces a critical challenge: its population is growing while its limited fertile land is shrinking due to urban sprawl on the Nile's irreplaceable floodplain." },
                { id: 37, name: 'Shenzhen High-Rise Boom', lat: 22.5, lon: 114.1, zoom: 10, year1: 2017, year2: 2023, description: 'Track continuing transformation of Shenzhen\'s urban landscape.', bands: ['A28', 'A42', 'A35'], mode: 'change', explainer: "This temporal comparison shows the world's fastest urban transformation. In 1980, Shenzhen was a fishing village of 30,000; today it's a tech megalopolis of 17+ million. Observe continued densification and expansion—a laboratory of unprecedented urbanization speed." },
                { id: 38, name: 'Mumbai Coastal Development', lat: 19.1, lon: 72.9, zoom: 10, year1: 2017, year2: 2024, description: 'Monitor land reclamation and coastal development in Mumbai.', bands: ['A29', 'A43', 'A36'], mode: 'change', explainer: "This 10-cluster analysis reveals Mumbai's diverse urban fabric. Different colors distinguish the planned colonial core, dense informal settlements (showing different textures), industrial zones, remaining vegetation, and water bodies. The variety of clusters reflects the socioeconomic complexity of a megacity with extreme inequality." },
                { id: 39, name: 'Singapore Land Reclamation', lat: 1.35, lon: 103.85, zoom: 11, year1: 2017, year2: 2024, description: 'Observe ongoing land reclamation projects expanding Singapore.', bands: ['A30', 'A44', 'A37'], mode: 'change', explainer: "Change detection shows how Singapore grows without a hinterland: by expanding into the sea. Dark areas reveal new land created by filling coastal waters with sand. Singapore has increased its land area by 25% through reclamation—a city-state pushing the limits of geographic constraints." },
                { id: 40, name: 'Addis Ababa Light Rail', lat: 9.0, lon: 38.75, zoom: 11, year1: 2017, year2: 2023, description: 'Track infrastructure development and urbanization in Ethiopia\'s capital.', bands: ['A31', 'A45', 'A38'], mode: 'change', explainer: "Change detection reveals Addis Ababa's expansion consuming surrounding farmland. Dark areas at the city edge show where smallholder farms have been converted to residential and commercial development. This peri-urban transition zone is where rural and urban meet, creating challenges for both farmers and new residents." },
                { id: 41, name: 'Jakarta Sinking City', lat: -6.2, lon: 106.85, zoom: 10, year1: 2017, year2: 2024, description: 'Monitor urban development in subsiding coastal Jakarta.', bands: ['A32', 'A46', 'A39'], mode: 'change', explainer: "This 10-cluster analysis reveals Jakarta's complex urban morphology shaped by centuries of history. Different clusters distinguish the historic colonial core, formal planned neighborhoods, informal settlements, and remaining ecological areas. The city faces existential threats from subsidence and sea level rise." },
                { id: 42, name: 'Riyadh Desert Expansion', lat: 24.7, lon: 46.7, zoom: 9, year1: 2017, year2: 2024, description: 'Track rapid urbanization and new development projects in Saudi Arabia\'s capital.', bands: ['A33', 'A47', 'A40'], mode: 'change', explainer: "You're viewing the world's ambitious megaprojects taking shape in Saudi Arabia's capital. Dark areas show massive construction and new development. Whether visionary or folly, these projects demonstrate humanity's capacity to fundamentally reshape landscapes according to new urban visions." },
                { id: 43, name: 'Nairobi Tech Hub Growth', lat: -1.3, lon: 36.85, zoom: 10, year1: 2018, year2: 2024, description: 'Monitor development of technology parks and housing in Nairobi.', bands: ['A34', 'A48', 'A41'], mode: 'change', explainer: "Change detection reveals Nairobi's expansion consuming surrounding farmland. Dark areas at the city edge show where development has replaced agricultural land. The growth of tech hubs and middle-class housing creates new urban patterns distinct from historical informal settlement expansion." },
                { id: 44, name: 'Ho Chi Minh City Expansion', lat: 10.8, lon: 106.6, zoom: 10, year1: 2017, year2: 2024, description: 'Observe satellite city and industrial zone development around HCMC.', bands: ['A35', 'A49', 'A42'], mode: 'change', explainer: "You're viewing continued transformation of Vietnam's commercial capital. Dark areas show new construction, waterfront development, and infrastructure expansion. Ho Chi Minh City exemplifies Southeast Asian urban development: rapid industrialization driving residential and commercial expansion." },
                { id: 45, name: 'Mexico City Air Quality', lat: 19.4, lon: -99.1, zoom: 10, year1: 2020, year2: 2020, description: 'Analyze urban heat island and development patterns in Mexico City.', bands: ['A36', 'A50', 'A43'], mode: 'embeddings', explainer: "This 10-cluster analysis reveals Mexico City's complex urban morphology shaped by 700 years of history. Different clusters distinguish the historic center (built on a drained lakebed), formal planned neighborhoods, informal settlements climbing hillsides, and remaining ecological areas. The ancient Aztec capital persists in modern urban patterns." }
            ]
        },
        {
            id: 'water',
            name: 'Water Resources & Hydrology',
            icon: '💧',
            scenarios: [
                { id: 46, name: 'Aral Sea Disaster', lat: 44.5, lon: 59.0, zoom: 8, year1: 2017, year2: 2024, description: 'Monitor the continuing shrinkage of the Aral Sea, one of Earth\'s worst environmental disasters.', bands: ['A37', 'A51', 'A44'], mode: 'change', explainer: "You're witnessing one of humanity's greatest environmental catastrophes. Dark areas show where the Aral Sea—once the world's fourth-largest lake—has disappeared since 2017. Soviet-era irrigation projects diverted the rivers feeding this inland sea, leaving behind a toxic desert of salt and agricultural chemicals." },
                { id: 47, name: 'Lake Mead Drought', lat: 36.2, lon: -114.4, zoom: 10, year1: 2017, year2: 2024, description: 'Track water level decline in Lake Mead, key Colorado River reservoir.', bands: ['A38', 'A52', 'A45'], mode: 'change', explainer: "Change detection reveals the expanding 'bathtub ring' around America's largest reservoir. Dark areas show newly exposed lakebed as water levels dropped to historic lows between 2017 and 2024. Lake Mead supplies water to 25 million people—its decline exposes the vulnerability of Western water supplies to megadrought." },
                { id: 48, name: 'Dead Sea Shrinking', lat: 31.5, lon: 35.5, zoom: 10, year1: 2017, year2: 2024, description: 'Observe the continuing decline of the Dead Sea water levels.', bands: ['A39', 'A53', 'A46'], mode: 'change', explainer: "You're viewing Earth's lowest point getting lower. Dark areas show shoreline retreat as the Dead Sea drops over 1 meter per year. The Jordan River that once fed it is now almost entirely diverted for agriculture, leaving the sea to evaporate into history while sinkholes swallow the retreating shore." },
                { id: 49, name: 'Lake Chad Basin', lat: 13.5, lon: 14.0, zoom: 8, year1: 2017, year2: 2023, description: 'Monitor the fluctuating extent of Lake Chad in the Sahel region.', bands: ['A00', 'A15', 'A08'], mode: 'change', explainer: "You're viewing a lake that has lost 90% of its water since the 1960s. Dark areas show continued shoreline retreat and exposed lakebed becoming desert. Lake Chad once supported 30 million people across four countries—its disappearance creates climate refugees and regional conflict over dwindling resources." },
                { id: 50, name: 'Three Gorges Reservoir', lat: 30.8, lon: 111.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore the massive Three Gorges Dam reservoir and surrounding landscape.', bands: ['A40', 'A54', 'A47'], mode: 'embeddings', explainer: "This clustering maps the world's largest hydroelectric project. Different colors distinguish the massive reservoir, dam infrastructure, surrounding mountains, and downstream river. The Three Gorges Dam generates 100 billion kWh annually but displaced 1.3 million people and permanently altered the Yangtze ecosystem." },
                { id: 51, name: 'Ganges River Flooding', lat: 25.5, lon: 85.0, zoom: 8, year1: 2019, year2: 2020, description: 'Compare monsoon flooding patterns along the Ganges River.', bands: ['A41', 'A55', 'A48'], mode: 'change', explainer: "This 10-cluster analysis maps the world's most densely populated river basin. Different colors distinguish active river channels, stable islands (chars), floodplain agriculture, and urban areas. Two hundred million people live on this dynamic landscape where rivers constantly reshape the land during annual monsoon floods." },
                { id: 52, name: 'Colorado River Delta', lat: 31.8, lon: -115.0, zoom: 9, year1: 2017, year2: 2024, description: 'Monitor water allocation impacts on the Colorado River delta.', bands: ['A42', 'A56', 'A49'], mode: 'change', explainer: "Change detection reveals the world's most overallocated river system. Dark areas show landscape changes as water rarely reaches the sea anymore. The Colorado River, which carved the Grand Canyon, now trickles to nothing before reaching the Gulf of California—a testament to human water demand." },
                { id: 53, name: 'Murray-Darling Basin', lat: -35.0, lon: 143.5, zoom: 8, year1: 2018, year2: 2021, description: 'Observe drought and recovery in Australia\'s major agricultural river system.', bands: ['A43', 'A57', 'A50'], mode: 'change', explainer: "You're viewing Australia's 'food bowl' during severe drought and partial recovery. Dark areas show how water scarcity transformed irrigated farmland between 2018 and 2021. The Murray-Darling Basin produces 40% of Australia's agricultural output—its vulnerability to drought has national economic and food security implications." },
                { id: 54, name: 'Mekong Dam Cascade', lat: 22.0, lon: 100.5, zoom: 8, year1: 2017, year2: 2023, description: 'Track impacts of hydropower dam construction on the upper Mekong.', bands: ['A44', 'A58', 'A51'], mode: 'change', explainer: "Change detection reveals how dam construction continues transforming the Mekong. Dark areas show reservoir filling, downstream flow changes, and landscape modifications. Major dams don't just flood valleys—they trigger decades of geomorphic adjustment as rivers seek new equilibrium states." },
                { id: 55, name: 'Lake Urmia Iran', lat: 37.7, lon: 45.5, zoom: 9, year1: 2017, year2: 2024, description: 'Monitor the dramatic shrinking of Iran\'s Lake Urmia.', bands: ['A45', 'A59', 'A52'], mode: 'change', explainer: "This temporal view shows Lake Urmia's continued decline. The dramatic color shift from blue (water) to tan (exposed lakebed) illustrates decades of water loss from irrigation diversions. What remains is a hypersaline remnant where a vast lake once supported fishing communities—a stark warning about large-scale water management consequences." },
                { id: 56, name: 'Brahmaputra River Dynamics', lat: 26.0, lon: 92.0, zoom: 8, year1: 2019, year2: 2020, description: 'Observe seasonal flooding and channel migration in Brahmaputra.', bands: ['A46', 'A60', 'A53'], mode: 'change', explainer: "Change detection reveals the world's most dynamic landscape—where nothing stays fixed. Dark areas show dramatic channel migration, island erosion, and new land formation. Villages that existed in 2019 may have been swallowed by rivers, while new land emerges elsewhere—a landscape in constant flux." },
                { id: 57, name: 'Salton Sea California', lat: 33.3, lon: -115.85, zoom: 10, year1: 2017, year2: 2024, description: 'Track the shrinking Salton Sea and exposed lakebed.', bands: ['A47', 'A61', 'A54'], mode: 'change', explainer: "Change detection tracks the largest ecosystem restoration challenge in California. Dark areas show the expanding exposed lakebed as the Salton Sea shrinks. This accidental lake, created by an irrigation accident in 1905, is now evaporating, exposing toxic dust that threatens public health in surrounding communities." },
                { id: 58, name: 'Poyang Lake Seasonal', lat: 29.2, lon: 116.2, zoom: 9, year1: 2020, year2: 2020, description: 'Explore China\'s largest freshwater lake seasonal variation patterns.', bands: ['A48', 'A62', 'A55'], mode: 'embeddings', explainer: "This clustering reveals how Africa's largest lake organizes surrounding land use. Different colors distinguish open water, papyrus swamps (crucial for water filtration), intensive agriculture, and expanding urban areas. Large lakes like these support millions of people but face eutrophication and invasive species threats." },
                { id: 59, name: 'Ogallala Aquifer Depletion', lat: 37.5, lon: -101.0, zoom: 8, year1: 2017, year2: 2024, description: 'Monitor center-pivot irrigation patterns and land use change over the Ogallala.', bands: ['A49', 'A63', 'A56'], mode: 'change', explainer: "This clustering highlights the distinctive circular patterns of center-pivot irrigation in the Great Plains. Each green circle is a field irrigated by a rotating sprinkler system drawing groundwater from the Ogallala Aquifer. The geometric precision of industrial agriculture transforms the landscape into a patchwork of perfect circles—but the aquifer is being depleted." },
                { id: 60, name: 'Lake Victoria Basin', lat: -1.5, lon: 33.5, zoom: 8, year1: 2020, year2: 2020, description: 'Analyze land use around Africa\'s largest lake.', bands: ['A00', 'A15', 'A08'], mode: 'embeddings', explainer: "This clustering maps a hydrological system supporting 40 million people. Different colors trace agricultural zones, urban areas, and remaining wetlands around Africa's largest lake. Lake Victoria's health—compromised by nutrient pollution and invasive species—serves as a bellwether for freshwater ecosystems worldwide." }
            ]
        },
        {
            id: 'coastal',
            name: 'Coastal & Marine Environments',
            icon: '🌊',
            scenarios: [
                { id: 61, name: 'Great Barrier Reef', lat: -18.0, lon: 147.0, zoom: 8, year1: 2020, year2: 2020, description: 'Explore coral reef patterns visible in AlphaEarth embeddings.', bands: ['A00', 'A31', 'A15'], mode: 'embeddings', explainer: "This clustering reveals the world's largest living structure: 2,300km of coral reef visible from space. Different colors distinguish reef platforms, lagoons, deep channels, and coastal zones. The reef's complexity—thousands of individual reefs forming a mosaic—appears as varied cluster patterns across the seascape." },
                { id: 62, name: 'Venice Lagoon', lat: 45.45, lon: 12.35, zoom: 11, year1: 2020, year2: 2020, description: 'Analyze the unique patterns of Venice\'s historic lagoon system.', bands: ['A01', 'A32', 'A16'], mode: 'embeddings', explainer: "This clustering maps the unique geography keeping Venice alive—and threatening its destruction. Different colors distinguish the city, lagoon waters of varying depths, barrier islands, and mainland. Venice exists in delicate equilibrium: too little water flow brings stagnation; too much brings flooding (acqua alta)." },
                { id: 63, name: 'Bangladesh Sundarbans', lat: 21.95, lon: 89.2, zoom: 9, year1: 2017, year2: 2024, description: 'Monitor erosion and change in the world\'s largest mangrove forest.', bands: ['A02', 'A33', 'A17'], mode: 'change', explainer: "This 8-cluster analysis maps the world's largest mangrove forest spanning India and Bangladesh. Different colors distinguish mangrove density gradients, tidal channels, and edge habitats. The Sundarbans protect millions from cyclone storm surges while harboring Bengal tigers and countless species." },
                { id: 64, name: 'Dutch Delta Works', lat: 51.65, lon: 4.0, zoom: 10, year1: 2020, year2: 2020, description: 'Explore the engineering marvel of Netherlands\' flood protection system.', bands: ['A03', 'A34', 'A18'], mode: 'embeddings', explainer: "This clustering maps Europe's largest tidal flat system where land and sea intermix. Different colors distinguish tidal mudflats (exposed at low tide), barrier islands, salt marshes, and diked polders. The Dutch Delta Works demonstrate millennia of expertise in living with—and modifying—dynamic coastal environments." },
                { id: 65, name: 'Maldives Atolls', lat: 4.2, lon: 73.5, zoom: 10, year1: 2020, year2: 2020, description: 'Analyze coral atoll patterns in the climate-threatened Maldives.', bands: ['A04', 'A35', 'A19'], mode: 'embeddings', explainer: "This clustering reveals the precarious geography of the world's lowest nation. Different colors distinguish reef platforms, atoll lagoons, narrow islands, and deep ocean. Most Maldivian land lies less than 1 meter above sea level—climate projections suggest much may be uninhabitable by 2100." },
                { id: 66, name: 'Louisiana Wetland Loss', lat: 29.5, lon: -90.5, zoom: 9, year1: 2017, year2: 2024, description: 'Track coastal erosion and wetland loss in Louisiana delta.', bands: ['A05', 'A36', 'A20'], mode: 'change', explainer: "You're viewing land literally disappearing into the Gulf of Mexico. Dark areas show wetlands converted to open water since 2017—Louisiana loses a football field of land every 100 minutes. This crisis results from levees preventing natural sediment deposition, subsidence, and sea level rise." },
                { id: 67, name: 'Palm Islands Dubai', lat: 25.12, lon: 55.13, zoom: 12, year1: 2020, year2: 2020, description: 'Explore the artificial Palm Jumeirah island development.', bands: ['A06', 'A37', 'A21'], mode: 'embeddings', explainer: "This clustering maps the artificial Palm Jumeirah island—one of the largest land reclamation projects ever undertaken. Different colors distinguish the palm fronds, trunk, crescent breakwater, and surrounding waters. Dubai demonstrates how wealth and engineering can create entirely new geographies from the sea." },
                { id: 68, name: 'Chesapeake Bay Estuary', lat: 37.5, lon: -76.0, zoom: 8, year1: 2020, year2: 2020, description: 'Analyze patterns in America\'s largest estuary ecosystem.', bands: ['A07', 'A38', 'A22'], mode: 'embeddings', explainer: "This 8-cluster analysis maps America's largest estuary. Different colors reveal the bay's waters, extensive marshlands, agricultural watershed, and urban development. Chesapeake Bay's health—compromised by nutrient pollution and development—serves as a bellwether for estuarine ecosystems worldwide." },
                { id: 69, name: 'Wadden Sea Tidal Flats', lat: 53.5, lon: 8.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore UNESCO World Heritage tidal flat ecosystem.', bands: ['A08', 'A39', 'A23'], mode: 'embeddings', explainer: "This clustering maps Europe's largest tidal flat system where land and sea intermix twice daily. Different colors distinguish tidal mudflats (exposed at low tide), barrier islands, salt marshes, and diked polders. The Wadden Sea is a UNESCO World Heritage site critical for migrating birds." },
                { id: 70, name: 'Hong Kong Reclamation', lat: 22.35, lon: 114.15, zoom: 11, year1: 2017, year2: 2024, description: 'Monitor ongoing land reclamation projects in Hong Kong.', bands: ['A09', 'A40', 'A24'], mode: 'change', explainer: "This 10-cluster analysis maps how humans have transformed a natural harbor. Different colors reveal reclaimed land, remaining harbor waters, urban density gradients, and surviving green spaces. Hong Kong has expanded its land area by 7% through reclamation—geography constrained by mountains and sea." },
                { id: 71, name: 'Red Sea Coral Reefs', lat: 27.5, lon: 34.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore unique heat-resistant coral reef patterns in Red Sea.', bands: ['A10', 'A41', 'A25'], mode: 'embeddings', explainer: "This clustering maps a coast where desert meets tropical sea. Different colors distinguish coral reefs, coastal salt flats (sabkhas), and barren mountains plunging to the sea. The Red Sea's coral reefs are among the world's most heat-tolerant—offering hope and genetic resources for climate adaptation elsewhere." },
                { id: 72, name: 'Mississippi River Delta', lat: 29.15, lon: -89.25, zoom: 10, year1: 2017, year2: 2024, description: 'Track land loss and delta dynamics at the Mississippi mouth.', bands: ['A11', 'A42', 'A26'], mode: 'change', explainer: "Change detection tracks transformation of this ecologically critical delta. Dark areas may indicate marsh loss, shoreline erosion, or oil/gas infrastructure impacts. The Mississippi delta is disappearing faster than almost any coastal landscape on Earth—a crisis with major ecological and economic consequences." },
                { id: 73, name: 'Bay of Fundy Tides', lat: 45.3, lon: -64.5, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze tidal patterns in world\'s highest tidal range location.', bands: ['A12', 'A43', 'A27'], mode: 'embeddings', explainer: "Change detection tracks ongoing evolution of glacially-deposited landforms. The Bay of Fundy has the world's highest tides—16 meters between high and low. This extreme tidal range shapes coastal ecosystems and offers potential for tidal power generation." },
                { id: 74, name: 'Danube Delta Romania', lat: 45.0, lon: 29.5, zoom: 9, year1: 2020, year2: 2020, description: 'Explore Europe\'s largest wetland and delta ecosystem.', bands: ['A13', 'A44', 'A28'], mode: 'embeddings', explainer: "This clustering maps London's relationship with its river across two millennia. The Danube Delta is Europe's largest wetland and a UNESCO Biosphere Reserve. Different colors distinguish open water, reed beds, floating islands, and agricultural areas." },
                { id: 75, name: 'Florida Keys Reef Tract', lat: 24.7, lon: -81.0, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze patterns in North America\'s only barrier coral reef.', bands: ['A14', 'A45', 'A29'], mode: 'embeddings', explainer: "This clustering maps North America's only barrier coral reef. Different colors distinguish reef zones, seagrass meadows, and island habitats. The Florida Keys reef has lost 90% of its coral since 1960 due to warming, disease, and pollution—making it a laboratory for reef restoration." }
            ]
        },
        {
            id: 'climate',
            name: 'Climate & Seasonal Patterns',
            icon: '🌡️',
            scenarios: [
                { id: 76, name: 'Arctic Sea Ice Edge', lat: 78.0, lon: 0.0, zoom: 5, year1: 2017, year2: 2023, description: 'Compare Arctic sea ice extent between years.', bands: ['A15', 'A46', 'A30'], mode: 'change', explainer: "Change detection reveals where Arctic sea ice has retreated. Dark areas show ice loss between 2017 and 2023. The Arctic is warming 2-4 times faster than the global average, with summer sea ice declining about 13% per decade—fundamentally altering this critical climate system." },
                { id: 77, name: 'Greenland Ice Sheet', lat: 72.0, lon: -40.0, zoom: 6, year1: 2017, year2: 2024, description: 'Monitor surface changes on the Greenland ice sheet.', bands: ['A16', 'A47', 'A31'], mode: 'change', explainer: "Change detection reveals where Greenland's ice sheet is losing mass. Dark areas around the edges show ablation zones where melting and calving remove ice. Greenland contains enough ice to raise global sea levels by 7 meters—and it's losing approximately 270 billion tons annually." },
                { id: 78, name: 'Sahel Greening Trend', lat: 14.0, lon: 0.0, zoom: 7, year1: 2017, year2: 2024, description: 'Track vegetation changes in the African Sahel region.', bands: ['A17', 'A48', 'A32'], mode: 'change', explainer: "This analysis tests a counterintuitive finding: parts of the Sahara's southern edge are getting greener, not drier. Dark areas show vegetation change—but whether they indicate recovery or degradation requires careful interpretation. The Sahel's future remains uncertain, with greening trends potentially masking ecosystem degradation." },
                { id: 79, name: 'Antarctic Peninsula', lat: -65.0, lon: -60.0, zoom: 6, year1: 2017, year2: 2024, description: 'Observe ice shelf changes on the warming Antarctic Peninsula.', bands: ['A18', 'A49', 'A33'], mode: 'change', explainer: "You're viewing Earth's fastest-warming region: the Antarctic Peninsula has warmed 3°C since 1950. Dark areas show ice shelf collapse, glacier retreat, and newly exposed ground. When ice shelves disintegrate, they remove the 'cork' holding back land ice—accelerating sea level rise contributions." },
                { id: 80, name: 'European Heatwave Impact', lat: 47.0, lon: 8.0, zoom: 7, year1: 2021, year2: 2022, description: 'Compare vegetation stress before and during major heatwave.', bands: ['A19', 'A50', 'A34'], mode: 'change', explainer: "Change detection tracks European glacier retreat between 2021 and 2022. Dark areas at glacier termini show where ice has disappeared—European glaciers are retreating rapidly. Vegetation colonizing newly exposed ground represents ecosystems migrating upslope as climate zones shift." },
                { id: 81, name: 'Himalayan Glacier Retreat', lat: 28.0, lon: 84.5, zoom: 9, year1: 2017, year2: 2024, description: 'Track glacier changes in the Nepal Himalaya.', bands: ['A20', 'A51', 'A35'], mode: 'change', explainer: "You're viewing 'Asia's Water Towers'—glaciers that supply water to 2 billion people. Dark areas show glacier retreat and expanding glacial lakes that can burst catastrophically. The Himalayas contain the largest ice mass outside polar regions—their fate will determine water security across the continent." },
                { id: 82, name: 'Amazon Drought Patterns', lat: -3.0, lon: -60.0, zoom: 7, year1: 2019, year2: 2023, description: 'Compare drought year impacts on Amazon forest.', bands: ['A21', 'A52', 'A36'], mode: 'change', explainer: "This temporal comparison shows Amazon forest response to drought years. Slide through years to watch vegetation stress spread and intensify. The unprecedented droughts are testing the Amazon's resilience—potentially pushing it toward a tipping point where rainforest transitions to savanna." },
                { id: 83, name: 'Australian Bushfire Season', lat: -33.0, lon: 150.5, zoom: 8, year1: 2019, year2: 2020, description: 'Track 2019-2020 Black Summer bushfire impacts.', bands: ['A22', 'A53', 'A37'], mode: 'change', explainer: "This analysis shows the impact of Australia's catastrophic 2019-2020 'Black Summer' bushfires. Dark areas indicate severe fire damage—an estimated 3 billion animals were killed or displaced. These fires were unprecedented in their intensity and extent, raising questions about climate change impacts on fire regimes." },
                { id: 84, name: 'Siberian Permafrost', lat: 68.0, lon: 145.0, zoom: 7, year1: 2017, year2: 2024, description: 'Monitor permafrost thaw impacts in Siberian landscapes.', bands: ['A23', 'A54', 'A38'], mode: 'change', explainer: "Change detection reveals the Arctic transformation called 'greening.' Dark areas show where shrubs are expanding into former tundra as permafrost thaws. This seemingly positive 'greening' actually indicates destabilization of ecosystems that store twice as much carbon as the atmosphere." },
                { id: 85, name: 'Indian Monsoon Patterns', lat: 22.0, lon: 78.0, zoom: 6, year1: 2019, year2: 2020, description: 'Compare monsoon vegetation response across India.', bands: ['A24', 'A55', 'A39'], mode: 'change', explainer: "Change detection reveals multiple stressors transforming the Indian subcontinent. Dark areas indicate vegetation changes from drought, flooding, and land use change. The monsoon's reliability—critical for feeding 1.4 billion people—is becoming more erratic as climate changes." },
                { id: 86, name: 'Patagonian Ice Fields', lat: -49.0, lon: -73.5, zoom: 8, year1: 2017, year2: 2024, description: 'Track glacier retreat in South American ice fields.', bands: ['A25', 'A56', 'A40'], mode: 'change', explainer: "You're viewing some of Earth's fastest-retreating glaciers. Dark areas show dramatic ice loss between 2017 and 2024—Patagonian glaciers lose ice even faster than many polar glaciers. The Southern Patagonian Ice Field, Earth's second-largest temperate ice mass, is a laboratory for understanding rapid glacial change." },
                { id: 87, name: 'Svalbard Arctic Warming', lat: 78.0, lon: 16.0, zoom: 8, year1: 2017, year2: 2024, description: 'Monitor rapid warming impacts on Svalbard archipelago.', bands: ['A26', 'A57', 'A41'], mode: 'change', explainer: "Change detection captures rapid Arctic warming impacts. Svalbard is warming faster than almost anywhere on Earth—winters are 7°C warmer than in the 1970s. Dark areas show glacier retreat, permafrost thaw, and vegetation changes as this High Arctic landscape transforms." },
                { id: 88, name: 'Alps Snow Cover', lat: 46.5, lon: 10.0, zoom: 8, year1: 2018, year2: 2023, description: 'Compare snow cover patterns in European Alps.', bands: ['A27', 'A58', 'A42'], mode: 'change', explainer: "This clustering maps the 'Third Pole'—the Alps contain significant ice outside polar regions. Different colors distinguish glaciers, rocky peaks, alpine meadows, and forested slopes. The Alps have lost half their glacier volume since 1900, with acceleration in recent decades." },
                { id: 89, name: 'Horn of Africa Drought', lat: 5.0, lon: 42.0, zoom: 7, year1: 2020, year2: 2022, description: 'Track severe drought impacts in East Africa.', bands: ['A28', 'A59', 'A43'], mode: 'change', explainer: "Change detection reveals a paradox: vegetation changes even as climate stress increases. Dark areas show the impacts of severe drought between 2020 and 2022. The Horn of Africa faced its worst drought in 40 years, affecting over 20 million people with food insecurity." },
                { id: 90, name: 'Canadian Arctic Thaw', lat: 69.0, lon: -105.0, zoom: 7, year1: 2017, year2: 2024, description: 'Monitor landscape changes as Arctic warms.', bands: ['A29', 'A60', 'A44'], mode: 'change', explainer: "Change detection captures the interplay of Arctic warming effects. Dark areas show permafrost thaw, lake drainage, shoreline erosion, and vegetation changes. The Canadian Arctic is a laboratory for understanding how frozen landscapes respond to rapid warming." }
            ]
        },
        {
            id: 'geology',
            name: 'Geology & Landforms',
            icon: '🏔️',
            scenarios: [
                { id: 91, name: 'Grand Canyon Layers', lat: 36.1, lon: -112.1, zoom: 11, year1: 2020, year2: 2020, description: 'Explore geological layer patterns visible in AlphaEarth.', bands: ['A30', 'A61', 'A45'], mode: 'embeddings', explainer: "This clustering reveals billions of years of Earth history exposed in canyon walls. Different colors correspond to distinct rock units—each representing different ancient environments from shallow seas to desert dunes. The Colorado River has carved a geological textbook readable from space." },
                { id: 92, name: 'Sahara Desert Dunes', lat: 24.0, lon: 10.0, zoom: 8, year1: 2020, year2: 2020, description: 'Analyze sand dune formation patterns in the Sahara.', bands: ['A31', 'A62', 'A46'], mode: 'embeddings', explainer: "This clustering maps one of Earth's oldest deserts, with landforms shaped over millions of years. Different colors distinguish various dune types: barchans (crescent), linear (seif), and star dunes. These patterns reflect prevailing wind directions and sand supply—geology written by atmosphere." },
                { id: 93, name: 'Himalayan Fold Mountains', lat: 28.5, lon: 84.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore tectonic patterns in Himalayan mountain structures.', bands: ['A32', 'A63', 'A47'], mode: 'embeddings', explainer: "This clustering reveals the internal organization of Earth's highest mountain range. Different colors distinguish glacier zones, exposed rock faces, vegetated slopes, and valley floors. The Himalayas continue rising as India pushes into Asia—active tectonics visible in folded rock patterns." },
                { id: 94, name: 'Iceland Volcanic Features', lat: 64.5, lon: -18.0, zoom: 8, year1: 2020, year2: 2020, description: 'Analyze volcanic landforms and lava fields of Iceland.', bands: ['A33', 'A00', 'A48'], mode: 'embeddings', explainer: "Change detection captures the interplay of Iceland's elemental forces. Different colors show glaciers, recent lava flows, older volcanic terrain, and vegetated areas. Iceland sits on the Mid-Atlantic Ridge where tectonic plates spread apart—a laboratory for understanding volcanic processes." },
                { id: 95, name: 'Australian Uluru Region', lat: -25.35, lon: 131.0, zoom: 10, year1: 2020, year2: 2020, description: 'Explore patterns around Uluru and Kata Tjuta.', bands: ['A34', 'A01', 'A49'], mode: 'embeddings', explainer: "This clustering maps the ancient heart of Australia. Different colors distinguish the iconic monoliths from surrounding desert plains. Uluru and Kata Tjuta are remnants of an ancient mountain range, now mostly buried beneath 600 million years of sediment—geological time made visible." },
                { id: 96, name: 'Death Valley Salt Flats', lat: 36.25, lon: -116.85, zoom: 10, year1: 2020, year2: 2020, description: 'Analyze salt pan patterns in Death Valley.', bands: ['A35', 'A02', 'A50'], mode: 'embeddings', explainer: "This clustering maps one of Earth's most extreme environments. Different colors distinguish salt flats, alluvial fans, and mountain slopes. Death Valley's Badwater Basin, at -86 meters, is the lowest point in North America—a landlocked basin where evaporation concentrates minerals into geometric salt polygons." },
                { id: 97, name: 'Ethiopian Rift Valley', lat: 7.5, lon: 39.0, zoom: 8, year1: 2020, year2: 2020, description: 'Explore tectonic features of the East African Rift.', bands: ['A36', 'A03', 'A51'], mode: 'embeddings', explainer: "You're viewing one of Earth's most extreme environments: the East African Rift Valley. Different colors distinguish volcanic terrain, rift lakes, and ancient plateaus. The rift is where Africa is slowly splitting apart—in millions of years, a new ocean will form here." },
                { id: 98, name: 'Namib Desert Patterns', lat: -24.5, lon: 15.5, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze unique dune patterns in the world\'s oldest desert.', bands: ['A37', 'A04', 'A52'], mode: 'embeddings', explainer: "This clustering maps the world's oldest desert—the Namib has been arid for 55-80 million years. Different colors distinguish the world's tallest sand dunes, gravel plains, ephemeral rivers, and coastal fog zones. The Namib's extreme aridity creates textbook examples of desert geomorphology." },
                { id: 99, name: 'Tibetan Plateau', lat: 33.0, lon: 90.0, zoom: 7, year1: 2020, year2: 2020, description: 'Explore patterns across the "Roof of the World".', bands: ['A38', 'A05', 'A53'], mode: 'embeddings', explainer: "This clustering maps the 'Roof of the World'—the Tibetan Plateau averages 4,500 meters elevation. Different colors distinguish high-altitude grasslands, permafrost lakes, glaciers, and cold desert. This frozen landscape stores water for billions and carbon that could accelerate warming if released." },
                { id: 100, name: 'Atacama Mineral Patterns', lat: -23.5, lon: -68.5, zoom: 9, year1: 2020, year2: 2020, description: 'Analyze mineral deposits visible in driest desert.', bands: ['A39', 'A06', 'A54'], mode: 'embeddings', explainer: "This clustering reveals the mysterious patterns of Earth's driest desert. Different colors distinguish various mineral deposits, salt flats, and volcanic terrain. The Atacama's extreme aridity preserves minerals and creates conditions so Mars-like that NASA tests rovers here." }
            ]
        },
        {
            id: 'historical',
            name: 'Historical & Archaeological',
            icon: '🏛️',
            scenarios: [
                { id: 101, name: 'Giza Pyramids Complex', lat: 29.975, lon: 31.13, zoom: 14, year1: 2020, year2: 2020, description: 'Explore the ancient Giza Pyramid complex patterns.', bands: ['A40', 'A07', 'A55'], mode: 'embeddings', explainer: "This clustering reveals the hidden extent of the ancient Egyptian civilization's footprint. Different colors trace temple complexes, the Nile floodplain, and modern Cairo encroaching on ancient sites. The pyramids' perfect geometry contrasts with organic urban patterns surrounding them." },
                { id: 102, name: 'Nazca Lines Peru', lat: -14.7, lon: -75.1, zoom: 13, year1: 2020, year2: 2020, description: 'Analyze patterns around the ancient Nazca geoglyphs.', bands: ['A41', 'A08', 'A56'], mode: 'embeddings', explainer: "This visualization attempts to reveal the famous Nazca Lines—ancient geoglyphs etched into Peru's desert plain. The narrow stretch parameters enhance subtle surface differences. These mysterious figures, some over 1,000 feet long, were created 2,000 years ago by removing iron-oxide coated pebbles to expose lighter ground beneath." },
                { id: 103, name: 'Angkor Wat Temple Complex', lat: 13.41, lon: 103.87, zoom: 13, year1: 2020, year2: 2020, description: 'Explore the largest religious monument complex.', bands: ['A42', 'A09', 'A57'], mode: 'embeddings', explainer: "This clustering reveals the hidden extent of the ancient Khmer Empire's water management. Different colors trace temple complexes, the massive baray (reservoir) system, and modern rice paddies that still use medieval irrigation channels. Angkor's sophisticated hydrology sustained a city of 1 million people—larger than any contemporary European city." },
                { id: 104, name: 'Ancient Irrigation Persia', lat: 32.0, lon: 54.0, zoom: 10, year1: 2020, year2: 2020, description: 'Analyze qanat irrigation patterns in Iranian plateau.', bands: ['A43', 'A10', 'A58'], mode: 'embeddings', explainer: "This clustering searches for traces of humanity's earliest civilizations. Different colors may distinguish oasis agriculture fed by ancient qanats (underground channels), modern irrigation, and desert. The qanat system, invented 3,000 years ago, still supplies water to Iranian cities today." },
                { id: 105, name: 'Roman Road Network', lat: 41.9, lon: 12.5, zoom: 9, year1: 2020, year2: 2020, description: 'Trace ancient Roman road patterns visible in landscape.', bands: ['A44', 'A11', 'A59'], mode: 'embeddings', explainer: "You're viewing 2,000-year-old Roman land surveying still shaping modern Italy. The grid pattern visible in clustering follows ancient Roman roads and field boundaries. Historical boundaries can persist in landscapes for millennia—the past remains legible in the present." },
                { id: 106, name: 'Machu Picchu Region', lat: -13.16, lon: -72.55, zoom: 13, year1: 2020, year2: 2020, description: 'Explore Incan terracing and site patterns.', bands: ['A45', 'A12', 'A60'], mode: 'embeddings', explainer: "This clustering maps the Incan heartland. Different colors distinguish ancient terracing, cloud forest, and high-altitude grasslands. The Incas engineered an empire in extreme terrain—their agricultural terraces still function today, demonstrating sophisticated understanding of microclimates and water management." },
                { id: 107, name: 'Great Wall of China', lat: 40.4, lon: 116.5, zoom: 11, year1: 2020, year2: 2020, description: 'Trace the Great Wall through varied landscapes.', bands: ['A46', 'A13', 'A61'], mode: 'embeddings', explainer: "This clustering traces humanity's largest construction project across varied terrain. Different colors distinguish the wall itself, agricultural valleys it protected, and the steppes beyond. The Great Wall represents 2,000 years of fortification—a border written in stone across diverse ecosystems." },
                { id: 108, name: 'Mesopotamia Ancient Cities', lat: 32.5, lon: 44.5, zoom: 9, year1: 2020, year2: 2020, description: 'Explore patterns of ancient settlement mounds in Iraq.', bands: ['A47', 'A14', 'A62'], mode: 'embeddings', explainer: "This clustering searches for traces of humanity's earliest civilizations. Different colors may distinguish tell mounds (archaeological sites rising above floodplains), ancient irrigation channels, and modern agriculture. Satellite archaeology has revealed thousands of previously unknown sites across ancient Mesopotamia." }
            ]
        },
        {
            id: 'disasters',
            name: 'Disaster Response & Hazards',
            icon: '⚠️',
            scenarios: [
                { id: 109, name: 'Tonga Volcano Aftermath', lat: -20.55, lon: -175.4, zoom: 10, year1: 2021, year2: 2022, description: 'Compare before/after the 2022 Hunga Tonga eruption.', bands: ['A48', 'A15', 'A63'], mode: 'change', explainer: "You're viewing the aftermath of the January 2022 eruption—the largest atmospheric explosion recorded by modern instruments. Dark areas show where the volcanic island was almost entirely destroyed, with only small remnants remaining. The eruption generated tsunami waves detected globally and a pressure wave that circled Earth multiple times." },
                { id: 110, name: 'Fukushima Exclusion Zone', lat: 37.45, lon: 141.0, zoom: 10, year1: 2017, year2: 2024, description: 'Monitor land use changes in Fukushima exclusion zone.', bands: ['A49', 'A16', 'A00'], mode: 'change', explainer: "This clustering maps the ongoing legacy of the 2011 nuclear disaster. Different colors distinguish the still-evacuated zone, decontaminated and reopened areas, and the coast where tsunami and earthquake damage occurred. Fourteen years later, over 30,000 people remain displaced from their homes." },
                { id: 111, name: 'Paradise California Fire', lat: 39.76, lon: -121.6, zoom: 12, year1: 2018, year2: 2024, description: 'Track rebuilding after devastating 2018 Camp Fire.', bands: ['A50', 'A17', 'A01'], mode: 'change', explainer: "Change detection shows the devastating 2018 Camp Fire that destroyed Paradise, California—the deadliest and most destructive wildfire in state history. Dark areas reveal complete obliteration of a town of 27,000 people. 85 people died and over 18,000 structures were destroyed in a fire that moved as fast as 80 football fields per minute." },
                { id: 112, name: 'Nepal Earthquake 2015', lat: 28.15, lon: 84.75, zoom: 10, year1: 2017, year2: 2023, description: 'Monitor post-earthquake reconstruction in Nepal.', bands: ['A51', 'A18', 'A02'], mode: 'change', explainer: "Change detection reveals urban destruction and recovery from the devastating 2015 earthquakes. Dark areas in mountainous regions show landslides and collapsed buildings. The magnitude 7.8 earthquake killed nearly 9,000 people—this view shows the long process of reconstruction and recovery." },
                { id: 113, name: 'Bahamas Hurricane Dorian', lat: 26.6, lon: -78.2, zoom: 10, year1: 2019, year2: 2022, description: 'Track recovery from devastating 2019 Hurricane Dorian.', bands: ['A52', 'A19', 'A03'], mode: 'change', explainer: "Change detection captures the catastrophic impact of Hurricane Dorian in September 2019. Dark areas show devastation—Dorian stalled over the Bahamas for 40 hours as a Category 5 hurricane, the strongest Atlantic hurricane to make landfall. Over 70,000 people were left homeless." },
                { id: 114, name: 'Australia Lake Fire Scars', lat: -36.0, lon: 149.0, zoom: 9, year1: 2019, year2: 2024, description: 'Monitor forest recovery from Black Summer fires.', bands: ['A53', 'A20', 'A04'], mode: 'change', explainer: "Change detection captures Pakistan's apocalyptic 2019-2020 fire season and recovery. Dark areas show the vast extent of fire damage—one-third of Australia's forests were affected. Over 3 billion animals were killed or displaced, and the fires raised fundamental questions about Australia's fire future." },
                { id: 115, name: 'Houston Harvey Flooding', lat: 29.75, lon: -95.35, zoom: 10, year1: 2017, year2: 2018, description: 'Compare before/after Hurricane Harvey flooding.', bands: ['A54', 'A21', 'A05'], mode: 'change', explainer: "Change detection reveals urban flooding from Hurricane Harvey in August 2017. Dark areas show neighborhoods inundated by record rainfall—over 60 inches in some areas. Harvey caused $125 billion in damage and killed over 100 people, exposing Houston's vulnerability to extreme precipitation." },
                { id: 116, name: 'Lombok Earthquake Impact', lat: -8.45, lon: 116.35, zoom: 10, year1: 2018, year2: 2022, description: 'Monitor recovery from 2018 Lombok earthquakes.', bands: ['A55', 'A22', 'A06'], mode: 'change', explainer: "Change detection shows the August 2023 wildfire that destroyed the historic town of Lahaina and recovery in the broader region. Dark areas reveal damage from the 2018 earthquake sequence that killed over 500 people. The view shows ongoing recovery and reconstruction efforts in this island community." }
            ]
        },
        {
            id: 'experiments',
            name: 'Visualization Experiments',
            icon: '🔬',
            scenarios: [
                { id: 117, name: 'Urban Heat Signatures', lat: 40.7, lon: -74.0, zoom: 10, year1: 2020, year2: 2020, description: 'Explore urban heat patterns in New York City embeddings.', bands: ['A56', 'A23', 'A07'], mode: 'embeddings', explainer: "This experiment uses specific band combinations to explore urban patterns. Different parts of the city show distinct signatures based on building density, vegetation cover, and land use. Urban areas have unique embedding patterns that distinguish them from natural landscapes." },
                { id: 118, name: 'Vegetation Index Analog', lat: -1.0, lon: 36.8, zoom: 9, year1: 2020, year2: 2020, description: 'Find band combinations that highlight vegetation like NDVI.', bands: ['A00', 'A08', 'A01'], mode: 'clustering', explainer: "This clustering analysis segments the landscape into distinct land cover types based on embedding similarity. Each color represents a different cluster: intact vegetation, degraded areas, bare soil, and water bodies. Notice how the algorithm automatically separates land types without being told what they are—this is unsupervised machine learning in action." },
                { id: 119, name: 'Water Body Detection', lat: 46.5, lon: -94.0, zoom: 8, year1: 2020, year2: 2020, description: 'Experiment with bands that highlight lakes in Minnesota.', bands: ['A57', 'A24', 'A08'], mode: 'embeddings', explainer: "This experiment uses bands that may highlight water bodies in the 'Land of 10,000 Lakes.' Different band combinations reveal different landscape properties—since each of the 64 bands captures different learned features. Compare this view to other band combinations to see how interpretation changes." },
                { id: 120, name: 'Snow vs Cloud Patterns', lat: 46.9, lon: 8.0, zoom: 9, year1: 2020, year2: 2020, description: 'Explore how embeddings differentiate snow from clouds.', bands: ['A58', 'A25', 'A09'], mode: 'embeddings', explainer: "This experiment explores how AlphaEarth embeddings distinguish between snow and clouds—a classic remote sensing challenge. The annual composite averages out clouds while preserving persistent snow. Different colors in snowy areas may indicate varying snow properties or underlying terrain." },
                { id: 121, name: 'Coastal Turbidity Patterns', lat: -23.0, lon: -43.2, zoom: 10, year1: 2020, year2: 2020, description: 'Analyze water turbidity patterns near Rio de Janeiro.', bands: ['A59', 'A26', 'A10'], mode: 'embeddings', explainer: "This experiment uses bands that may highlight water properties. Coastal waters show varying signatures based on turbidity, depth, and bottom type. The distinct patterns visible depend on what features these particular embedding dimensions encode—something the AI learned during training." },
                { id: 122, name: 'Agricultural Stress Detection', lat: 36.0, lon: -119.5, zoom: 9, year1: 2021, year2: 2022, description: 'Compare drought stress patterns in California crops.', bands: ['A60', 'A27', 'A11'], mode: 'change', explainer: "This experiment compares consecutive years to detect agricultural stress. Dark areas may indicate fields that were fallowed, switched crops, or experienced drought stress. Change detection between years reveals the dynamic human decisions embedded in agricultural landscapes." },
                { id: 123, name: 'Land Cover Clustering', lat: 51.5, lon: -0.1, zoom: 10, year1: 2020, year2: 2020, description: 'Use clustering to identify land cover types around London.', bands: ['A00', 'A15', 'A08'], mode: 'clustering', explainer: "This experiment uses clustering to segment Greater London into land cover types. More clusters can reveal subtle variations invisible with fewer categories—urban density gradients, park types, and industrial areas each get distinct colors. The 'right' number of clusters depends on your analytical question." },
                { id: 124, name: 'Temporal Stability Analysis', lat: 35.7, lon: 139.7, zoom: 10, year1: 2017, year2: 2024, description: 'Find areas of high change vs stability in Tokyo region.', bands: ['A61', 'A28', 'A12'], mode: 'change', explainer: "This experiment uses change detection to find the most stable and dynamic areas. White areas have barely changed—mature urban fabric with established infrastructure. Dark areas show construction, redevelopment, or land use change. This reveals where the city is growing versus where it's stable." },
                { id: 125, name: 'Embedding Space Explorer', lat: 0.0, lon: 0.0, zoom: 2, year1: 2020, year2: 2020, description: 'Freely explore the 64-dimensional embedding space globally.', bands: ['A62', 'A29', 'A13'], mode: 'embeddings', explainer: "This experiment loads a global view for comprehensive exploration. Use the band selectors to try different combinations and see how different parts of the embedding space represent different landscape features. The 64 dimensions encode learned features—experimentation reveals what each captures." }
            ]
        }
    ],

    /**
     * Get all scenarios
     * @returns {Array} All scenarios across categories
     */
    getAllScenarios() {
        const scenarios = [];
        this.categories.forEach(cat => {
            cat.scenarios.forEach(s => {
                scenarios.push({
                    ...s,
                    category: cat.id,
                    categoryName: cat.name,
                    categoryIcon: cat.icon
                });
            });
        });
        return scenarios;
    },

    /**
     * Get scenarios by category
     * @param {string} categoryId - Category ID
     * @returns {Array} Scenarios in category
     */
    getByCategory(categoryId) {
        const category = this.categories.find(c => c.id === categoryId);
        return category ? category.scenarios : [];
    },

    /**
     * Get scenario by ID
     * @param {number} id - Scenario ID
     * @returns {Object|null} Scenario or null
     */
    getById(id) {
        for (const cat of this.categories) {
            const scenario = cat.scenarios.find(s => s.id === id);
            if (scenario) {
                return {
                    ...scenario,
                    category: cat.id,
                    categoryName: cat.name,
                    categoryIcon: cat.icon
                };
            }
        }
        return null;
    },

    /**
     * Search scenarios by keyword
     * @param {string} query - Search query
     * @returns {Array} Matching scenarios
     */
    search(query) {
        const lowerQuery = query.toLowerCase();
        return this.getAllScenarios().filter(s =>
            s.name.toLowerCase().includes(lowerQuery) ||
            s.description.toLowerCase().includes(lowerQuery)
        );
    }
};

// Export
window.CaseStudies = CaseStudies;
